---
name: Changelog Pipeline

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

  workflow_dispatch:

jobs:
  update-changelog2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate unreleased changelog
        uses: orhun/git-cliff-action@v3
        id: generate_unreleased_changelog
        with:
          config: ./cliff.toml
          args: --unreleased --bump
        env:
          OUTPUT: CHANGELOG.md

      - name: Print the changelog
        run: cat "${{ steps.generate_unreleased_changelog.outputs.changelog }}"

      - name: Update CHANGELOG.md
        id: update_changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: ./cliff.toml
          args: --bump
        env:
          OUTPUT: CHANGELOG.md

      # - name: Commit and push changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "chore(changelog): update changelog [skip ci]"

      - name: Print New Tag
        id: print_new_tag
        run: |
          echo "New Tag: v${{ steps.generate_unreleased_changelog.outputs.version }}"

      - name: release
        uses: actions/create-release@v1
        with:
          release_name: Release v${{ steps.generate_unreleased_changelog.outputs.version }}
          tag_name: v${{ steps.generate_unreleased_changelog.outputs.version }}
          commitish: ${{ github.sha }}
          body: ${{ steps.generate_unreleased_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Format changelog for Slack
        id: format_for_slack
        run: |
          output=$(python scripts/changelog_slack.py ${{ steps.generate_unreleased_changelog.outputs.changelog }})
          echo "::set-output name=formatted_json::$output"
          echo "Formatted JSON output for debugging: $output"
          echo "Changelog for debugging: ${{ steps.generate_unreleased_changelog.outputs.changelog }}"
        env:
          UNRELEASED_CHANGELOG: ${{ steps.generate_unreleased_changelog.outputs.changelog }}

      - name: Send custom JSON data to Slack workflow
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: "C06N79SSDD5"
          payload: ${{ steps.format_for_slack.outputs.formatted_json }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
